### ISSUE TITLE
Provide a way to set the resource limits in the systemd unit files

### ISSUE THREAD

**Issue by kulikovav** [funbox/init-exporter#4]
Systemd has its own resource control options: https://www.freedesktop.org/software/systemd/man/systemd.exec.html
```
LimitCPU=, LimitFSIZE=, LimitDATA=, LimitSTACK=, LimitCORE=, LimitRSS=, LimitNOFILE=, LimitAS=, LimitNPROC=, LimitMEMLOCK=, LimitLOCKS=, LimitSIGPENDING=, LimitMSGQUEUE=, LimitNICE=, LimitRTPRIO=, LimitRTTIME=
```
We need to set LimitNOFILE and LimitNPROC to something different than default values.
Also it would be great to make them configurable by user.

**Comment by andyone** [comment]
Added this feature in 4c66b4741b9d291f968ecd93044c2a726ed61991 for systemd and upstart exporters.

Now custom limits can be defined globally in init-exporter [configuration file](https://github.com/funbox/init-exporter/blob/develop/common/init-exporter.conf#L28) (_10k for both by default_) and can be redefined for [application](https://github.com/funbox/init-exporter/blob/develop/testdata/procfile_v2#L14) or [service](https://github.com/funbox/init-exporter/blob/develop/testdata/procfile_v2#L32) in procfile (_only v2_).
