### ISSUE TITLE
Add Python version manager (pyenv)

### ISSUE THREAD

**Issue by gongled** [funbox/init-exporter#45]
### Feature Request

**Proposal:**

Add `pyenv` version manager for Python in addition to `rbenv` to `init-exporter` on the analogy of `rbenv`.

**Current behavior:**

`pyenv` is not supported by `init-exporter`.

**Desired behavior:**

Would be nice to have the following line in the helper program:
```
[[ -r /etc/profile.d/pyenv.sh ]] && source /etc/profile.d/pyenv.sh
```

**Use case:**

It would allow use Python-written programs using `pyenv` without a necessity to craft a wrapper on application level that exports environment variables.

**Comment by andyone** [comment]
Added in #44

**Comment by andyone** [comment]
Version 0.19.0 released

**Comment by gongled** [comment]
Thank you! 🎉
