### ISSUE TITLE
[Feature Request] Add LimitMEMLOCK option

### ISSUE THREAD

**Issue by ILoGM** [funbox/init-exporter#53]
Hi!
We'd love to have configurable in procfile LimitMEMLOCK option because some services/utils (e.g. elastic) demand to customise it. 
I found limits parsing in source code [here](https://github.com/funbox/init-exporter/blob/master/procfile/procfile_v2.go#L267), but there is no MEMLOCK support. Hope you'll find it reasonable to add it.

**Comment by andyone** [comment]
`init-exporter-0.21.0` with this feature has added to the `testing` repository.
