### ISSUE TITLE
Upstart: reload_signal does not work on CentOS 6

### ISSUE THREAD

**Issue by gongled** [funbox/init-exporter#56]
### Bug report

**System info:**

* **Version used:** 0.21.0
* **OS (`cat /etc/*-release`):** CentOS 6
* **Kernel (`uname -a`):** `2.6.32`

**System info:**

1. Create `Procfile` with the `reload_signal` option defined.
2. Export given procfile to upstart.
3. Start upstart job.
4. Run `reload` command using `initctl`.

**Expected behavior:**

Command `reload` sends defined signal to the process.

**Actual behavior:**

Upstart configuration is broken with the `Unknown stanza` message. Upstart job cannot be started.

**Additional info:**

Issue happens due to unsupported stanza `reload` in upstart 0.6.5 that ships with CentOS 6 distro.

Possible solutions:
1. Remove this feature for upstart-driven systems.
2. Verify upstart version installed and forbid using this feature.
3. Check configuration using `init-checkconf` utility (does not exist on CentOS 6).
4. Update `upstart` to the latest stable version (sic!) and verify `upstart` version installed.

**Comment by andyone** [comment]
Thanks for your report! Unfortunately, `reload_signal` support removed in f147eec

**Comment by andyone** [comment]
Reimplemented in https://github.com/funbox/init-exporter/pull/55/commits/a489526bf8179a1fb7518e7f5173d7466f88cdb5
