### ISSUE TITLE
Systemd: reload_signal for CentOS 7

### ISSUE THREAD

**Issue by lunahike** [funbox/init-exporter#58]
Continuing the issue https://github.com/funbox/init-exporter/issues/57

### Feature Request

**Proposal:**

Return setting reload_signal for CentOS 7 (systemctl). Use it in the property `ExecReload`. Use the command `pkill` instead `kill`.
```
ExecReload=/bin/pkill -SIGUSR2 -P $MAINPID
```

**Current behavior:**

reload_signal is not supported

**Desired behavior:**

I would like to, when executing the command `systemctl reload` sends defined signal to the process.

**Comment by andyone** [comment]
Implemented in 0903f5a9d38ae52d603fd8bb649e7cc84f610a3b
